In [70]:
import os 
import numpy as np 
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
folder_path = 'train_images/'
#listOfImages = os.listdir(folder_path)
#print(listOfImages)
img_width, img_height = 320, 240

train_images = []
train_labels=[]
for img in os.listdir(folder_path):
    train_labels.append(img)
    img=folder_path+img
    #print(img)
    img = load_img(img, target_size=(img_width, img_height))
    img = img_to_array(img)
    img = np.expand_dims(img, axis=0)
    train_images.extend(img)
# img1 = listOfImages[0]
# print(img1)
# url = folder_path+img1
# myPic = load_img(url, target_size=(img_width, img_height))

In [71]:
train_labels

['ahmer (1).jpg',
 'ahmer (2).jpg',
 'ahmer (3).jpg',
 'ahmer (4).jpg',
 'fayyaz  (1).jpg',
 'fayyaz  (2).jpg',
 'fayyaz  (3).jpg',
 'fayyaz  (5).jpg',
 'kashan  (1).jpg',
 'kashan  (2).jpg',
 'kashan  (3).jpg',
 'kashan  (4).jpg',
 'kashan  (5).jpg',
 'mansoor  (1).jpg',
 'mansoor  (2).jpg',
 'mansoor  (3).jpg',
 'mansoor  (4).jpg',
 'sachin  (1).jpg',
 'sachin  (2).jpg',
 'sachin  (3).jpg',
 'sachin  (5).jpg',
 'shaheer (1).jpg',
 'shaheer (2).jpg',
 'shaheer (3).jpg',
 'shaheer (4).jpg',
 'shaheer (5).jpg',
 'sir (1).jpg',
 'sir (2).jpg',
 'sir (3).jpg',
 'sir (4).jpg',
 'tehami (1).jpg',
 'tehami (2).jpg',
 'tehami (3).jpg',
 'tehami (4).jpg',
 'wahab (1).jpg',
 'wahab (2).jpg',
 'wahab (3).jpg',
 'wahab (4).jpg']

In [72]:
train_labels = np.array(train_labels)
train_labels.shape

(38,)

In [73]:
train_labels

array(['ahmer (1).jpg', 'ahmer (2).jpg', 'ahmer (3).jpg', 'ahmer (4).jpg',
       'fayyaz  (1).jpg', 'fayyaz  (2).jpg', 'fayyaz  (3).jpg',
       'fayyaz  (5).jpg', 'kashan  (1).jpg', 'kashan  (2).jpg',
       'kashan  (3).jpg', 'kashan  (4).jpg', 'kashan  (5).jpg',
       'mansoor  (1).jpg', 'mansoor  (2).jpg', 'mansoor  (3).jpg',
       'mansoor  (4).jpg', 'sachin  (1).jpg', 'sachin  (2).jpg',
       'sachin  (3).jpg', 'sachin  (5).jpg', 'shaheer (1).jpg',
       'shaheer (2).jpg', 'shaheer (3).jpg', 'shaheer (4).jpg',
       'shaheer (5).jpg', 'sir (1).jpg', 'sir (2).jpg', 'sir (3).jpg',
       'sir (4).jpg', 'tehami (1).jpg', 'tehami (2).jpg',
       'tehami (3).jpg', 'tehami (4).jpg', 'wahab (1).jpg',
       'wahab (2).jpg', 'wahab (3).jpg', 'wahab (4).jpg'], dtype='<U16')

In [74]:
train_images= np.array(train_images)
train_images.shape

(38, 320, 240, 3)

In [75]:
train_images

array([[[[119., 107.,  69.],
         [115., 103.,  65.],
         [111., 103.,  66.],
         ...,
         [175., 175., 123.],
         [176., 176., 124.],
         [164., 164., 112.]],

        [[125., 113.,  73.],
         [116., 104.,  66.],
         [113., 104.,  65.],
         ...,
         [173., 171., 122.],
         [166., 164., 113.],
         [168., 166., 115.]],

        [[116., 107.,  66.],
         [115., 103.,  63.],
         [121., 109.,  69.],
         ...,
         [179., 179., 129.],
         [184., 182., 133.],
         [177., 175., 124.]],

        ...,

        [[144., 146., 141.],
         [138., 139., 134.],
         [144., 141., 136.],
         ...,
         [199., 207., 210.],
         [195., 203., 206.],
         [203., 211., 214.]],

        [[149., 151., 146.],
         [127., 126., 122.],
         [147., 148., 142.],
         ...,
         [197., 205., 208.],
         [202., 210., 213.],
         [200., 208., 211.]],

        [[145., 146., 141.],
       

In [76]:
import os 
import numpy as np 
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img
folder_path = 'test_images/'
#listOfImages = os.listdir(folder_path)
#print(listOfImages)
img_width, img_height = 320, 240

test_images = []
test_labels=[]
for img in os.listdir(folder_path):
    test_labels.append(img)
    img=folder_path+img
    #print(img)
    img = load_img(img, target_size=(img_width, img_height))
    img = img_to_array(img)
    img = np.expand_dims(img, axis=0)
    test_images.extend(img)
# img1 = listOfImages[0]
# print(img1)
# url = folder_path+img1
# myPic = load_img(url, target_size=(img_width, img_height))

In [77]:
test_images=np.array(test_images)

In [78]:
test_images.shape

(9, 320, 240, 3)

In [105]:
test_labels

array(['ahmer (5).jpg', 'fayyaz  (4).jpg', 'kashan  (6).jpg',
       'mansoor  (5).jpg', 'sachin  (4).jpg', 'shaheer (4).jpg',
       'sir (5).jpg', 'tehami (5).jpg', 'wahab (5).jpg'], dtype='<U16')

In [80]:
test_labels= np.array(test_labels)

In [81]:
test_labels.shape

(9,)

In [82]:
from keras import layers
from keras import models

In [83]:
# train_images=list(train_images)
# for img in train_images:
#     train_images.append(img.reshape(320*240,3))

In [84]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(320, 240, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='softmax'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(9, activation='softmax'))

model.summary()

In [85]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_17 (Conv2D)           (None, 318, 238, 32)      896       
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 159, 119, 32)      0         
_________________________________________________________________
conv2d_18 (Conv2D)           (None, 157, 117, 64)      18496     
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 78, 58, 64)        0         
_________________________________________________________________
conv2d_19 (Conv2D)           (None, 76, 56, 64)        36928     
_________________________________________________________________
flatten_4 (Flatten)          (None, 272384)            0         
_________________________________________________________________
dense_7 (Dense)              (None, 64)                17432640  
__________

In [86]:
train_images[0].reshape(320*240,3)

array([[119., 107.,  69.],
       [115., 103.,  65.],
       [111., 103.,  66.],
       ...,
       [197., 205., 208.],
       [198., 206., 209.],
       [200., 210., 212.]], dtype=float32)

In [87]:
from keras import optimizers
model.compile(loss='categorical_crossentropy', optimizer=optimizers.RMSprop(lr=1e-4), metrics=['acc'])

In [88]:
train_labels

array(['ahmer (1).jpg', 'ahmer (2).jpg', 'ahmer (3).jpg', 'ahmer (4).jpg',
       'fayyaz  (1).jpg', 'fayyaz  (2).jpg', 'fayyaz  (3).jpg',
       'fayyaz  (5).jpg', 'kashan  (1).jpg', 'kashan  (2).jpg',
       'kashan  (3).jpg', 'kashan  (4).jpg', 'kashan  (5).jpg',
       'mansoor  (1).jpg', 'mansoor  (2).jpg', 'mansoor  (3).jpg',
       'mansoor  (4).jpg', 'sachin  (1).jpg', 'sachin  (2).jpg',
       'sachin  (3).jpg', 'sachin  (5).jpg', 'shaheer (1).jpg',
       'shaheer (2).jpg', 'shaheer (3).jpg', 'shaheer (4).jpg',
       'shaheer (5).jpg', 'sir (1).jpg', 'sir (2).jpg', 'sir (3).jpg',
       'sir (4).jpg', 'tehami (1).jpg', 'tehami (2).jpg',
       'tehami (3).jpg', 'tehami (4).jpg', 'wahab (1).jpg',
       'wahab (2).jpg', 'wahab (3).jpg', 'wahab (4).jpg'], dtype='<U16')

In [92]:
# from keras.utils import to_categorical
# train_labels = to_categorical(train_labels)

In [99]:
train_labels_test=[0,0,0,0,1,1,1,1,2,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,5,6,6,6,6,7,7,7,7,8,8,8,8]
print(train_labels_test)

[0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8]


In [100]:
from keras.utils import to_categorical
train_labels_test = to_categorical(train_labels_test)
train_labels_test

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0.

In [101]:
model.fit(train_images, train_labels_test, epochs=5, batch_size=128)

Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
Epoch 1/5
38/38 [==============================] - 15s 382ms/step - loss: 2.1897 - acc: 0.1053
Epoch 2/5
38/38 [==============================] - 10s 252ms/step - loss: 2.4201 - acc: 0.1316
Epoch 3/5
38/38 [==============================] - 10s 254ms/step - loss: 2.2347 - acc: 0.1316
Epoch 4/5
38/38 [==============================] - 10s 252ms/step - loss: 2.4761 - acc: 0.1842
Epoch 5/5
38/38 [==============================] - 9s 249ms/step - loss: 1.8467 - acc: 0.3947


In [107]:
test_labels_test=[0,1,2,3,4,5,6,7,8]

In [109]:
from keras.utils import to_categorical
test_labels_test = to_categorical(test_labels_test)
test_labels_test

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [110]:
test_loss, test_acc = model.evaluate(test_images, test_labels_test)

9/9 [==============================] - 1s 115ms/step


In [111]:
print("Test Loss: ", test_loss)

Test Loss:  2.705195426940918


In [115]:
print("Test Accuracy: ", test_acc)

Test Accuracy:  0.1111111119389534


In [117]:
train_loss, train_acc = model.evaluate(train_images, train_labels_test)

38/38 [==============================] - 4s 96ms/step


In [118]:
print("Train Loss: ", train_loss)

Train Loss:  2.3876535641519645


In [119]:
print("Train Accuracy: ", train_acc)

Train Accuracy:  0.21052631578947367
